#!/bin/sh
if [ ! -d dep ]
then
    echo "No 'dep' directory... did you run ./install?"
    exit 1
fi
nose=dep/bin/nosetests
if [ ! -f "$nose" ]
then
	nose=`which nosetests`
fi
exec dep/bin/python $nose tests $@
